### ISSUE TITLE
reach

### ISSUE THREAD

**Issue by xkeksi** [Incognitolol/Hydro#3]
why do you bruteforce? its useless you have a tracker you could easily abuse this check to get a bit more reach

you know whenever the player sents or receives the sneak packet
also add 1.8+ support

**Comment by gbomexify** [comment]
Live, love, bruteforce. But I guess someone didn't read the README. The ac most likely won't be maintained unless there's interest in it, don't really plan on doing 1.8+ support it's not hard, but we have other things to do.

**Comment by gbomexify** [comment]
Showcase you abusing it please.

**Comment by Incognitolol** [comment]
> why do you bruteforce? its useless you have a tracker you could easily abuse this check to get a bit more reach
> 
> you know whenever the player sents or receives the sneak packet also add 1.8+ support

No, we will most likely not be adding support for any modern versions only legacy versions. Maybe in the future.

Now can you explain how you can abuse this check to get a bit more reach? We've done some extensive testing, and debugging to make sure it's as accurate as it can possibly get without giving people the full concept of how it should be done. I think it's like (0.03) off cause of the lazy fix for 0.03 but most ACs devs that I know of do it that way anyway. If you could showcase a video of abusing it please DM me on discord with it. (rnoincognito) and we'll solve the issues!
